name: Build/Deploy Branch to Staging
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  RACK_ENV: stage
  ENV_FILE: .env.stage

jobs:
  vars:
    runs-on: ubuntu-latest 
    outputs:
      REPOSITORY: ${{ steps.extract_variables.outputs.REPOSITORY }}
      LATEST_RELEASE: ${{ steps.octokit.outputs.tag }}
      BRANCH: ${{ steps.extract_variables.outputs.BRANCH }}
      TAG: ${{ steps.extract_variables.outputs.TAG }}
      GIT_SHA: ${{ steps.extract_variables.outputs.GIT_SHA }}
      GIT_SHA_SHORT: ${{ steps.extract_variables.outputs.GIT_SHA_SHORT }}
      MESSAGE: ${{ steps.extract_variables.outputs.MESSAGE }}
      SITE_URL: ${{ steps.dotenv.outputs.SITE_URL }}
      SITE_NAME: ${{ steps.dotenv.outputs.SITE_NAME }}
      RACK_ENV: ${{ env.RACK_ENV }}
      ENV_FILE: ${{ env.ENV_FILE }}
    env:
      REPOSITORY_1: "abcd"

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Get latest release tag
      uses: oprypin/find-latest-tag@v1
      with:
        repository: ${{ github.repository }}
        releases-only: true 
      id: octokit      
    - name: GET .env
      run: |
        cp ${{ env.ENV_FILE }} .env
    - name: Dotenv action
      uses: falti/dotenv-action@v1.0.4
      id: dotenv   
    - name: Extract variables
      shell: bash
      run: |
        echo "REPOSITORY=${{ github.repository }}" >> $GITHUB_OUTPUT
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "LATEST_RELEASE=${{ steps.octokit.outputs.tag }}" >> $GITHUB_OUTPUT
        echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "GIT_SHA_SHORT=$( git rev-parse --short ${{ github.sha }} )" >> $GITHUB_OUTPUT
        echo "MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT
        echo "SITE_NAME=${{ steps.dotenv.outputs.SITE_NAME }}" >> $GITHUB_OUTPUT
        echo "SITE_URL=${{ steps.dotenv.outputs.SITE_URL }}" >> $GITHUB_OUTPUT
        echo "RACK_ENV=${{ env.RACK_ENV }}" >> $GITHUB_OUTPUT
        echo "ENV_FILE=${{ env.ENV_FILE }}" >> $GITHUB_OUTPUT
      id: extract_variables  
      
    - name: Print variables
      run: |
        echo "REPOSITORY_1 = $REPOSITORY_1"
        echo "REPOSITORY = $REPOSITORY"
        echo "BRANCH = $BRANCH"
        echo "LATEST_RELEASE = $LATEST_RELEASE"
        echo "TAG = $TAG"
        echo "GIT_SHA = $GIT_SHA"
        echo "GIT_SHA_SHORT = $GIT_SHA_SHORT"
        echo "MESSAGE = $MESSAGE"
        echo "SITE+NAME = $SITE_NAME"
        echo "SITE_URL = $SITE_URL"
        echo "RACK_ENV = $RACK_ENV"
        echo "ENV_FILE = $ENV_FILE"
        echo "GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER"
        echo "GITHUB_WORKFLOW = $GITHUB_WORKFLOW"

  build:
    needs: [vars]
    uses: ./.github/workflows/build.yml
    with:
      REPOSITORY: ${{ needs.vars.outputs.REPOSITORY }}
      LATEST_RELEASE: ${{ needs.vars.outputs.LATEST_RELEASE }}
      BRANCH: ${{ needs.vars.outputs.BRANCH }}
      TAG: ${{ needs.vars.outputs.TAG }}
      GIT_SHA: ${{ needs.vars.outputs.GIT_SHA }}
      GIT_SHA_SHORT: ${{ needs.vars.outputs.GIT_SHA_SHORT }}
      MESSAGE: ${{ needs.vars.outputs.MESSAGE }}
      SITE_NAME: ${{ needs.vars.outputs.SITE_NAME }}
      SITE_URL: ${{ needs.vars.outputs.SITE_URL }}
      RACK_ENV: ${{ needs.vars.outputs.RACK_ENV }}
      ENV_FILE: ${{ needs.vars.outputs.ENV_FILE }}
    secrets:
      S3_BUCKET: ${{ secrets.STAGE_S3_BUCKET }}
      S3_REGION: ${{ secrets.STAGE_S3_BUCKET_REGION }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  deploy:
    needs: [vars, build]
    uses: ./.github/workflows/deploy.yml
    with:
      REPOSITORY: ${{ needs.vars.outputs.REPOSITORY }}
      LATEST_RELEASE: ${{ needs.vars.outputs.LATEST_RELEASE }}
      BRANCH: ${{ needs.vars.outputs.BRANCH }}
      TAG: ${{ needs.vars.outputs.TAG }}
      GIT_SHA: ${{ needs.vars.outputs.GIT_SHA }}
      GIT_SHA_SHORT: ${{ needs.vars.outputs.GIT_SHA_SHORT }}
      MESSAGE: ${{ needs.vars.outputs.MESSAGE }}
      SITE_NAME: ${{ needs.vars.outputs.SITE_NAME }}
      SITE_URL: ${{ needs.vars.outputs.SITE_URL }}
      RACK_ENV: ${{ needs.vars.outputs.RACK_ENV }}
      ENV_FILE: ${{ needs.vars.outputs.ENV_FILE }}
    secrets:
      S3_BUCKET: ${{ secrets.STAGE_S3_BUCKET }}
      S3_REGION: ${{ secrets.STAGE_S3_BUCKET_REGION }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify:
    needs: [vars, build, deploy]
    uses: ./.github/workflows/notify.yml
    with:
      REPOSITORY: ${{ needs.vars.outputs.REPOSITORY }}
      LATEST_RELEASE: ${{ needs.vars.outputs.LATEST_RELEASE }}
      BRANCH: ${{ needs.vars.outputs.BRANCH }}
      TAG: ${{ needs.vars.outputs.TAG }}
      GIT_SHA: ${{ needs.vars.outputs.GIT_SHA }}
      GIT_SHA_SHORT: ${{ needs.vars.outputs.GIT_SHA_SHORT }}
      MESSAGE: ${{ needs.vars.outputs.MESSAGE }}
      SITE_NAME: ${{ needs.vars.outputs.SITE_NAME }}
      SITE_URL: ${{ needs.vars.outputs.SITE_URL }}
      RACK_ENV: ${{ needs.vars.outputs.RACK_ENV }}
      ENV_FILE: ${{ needs.vars.outputs.ENV_FILE }}
    secrets:
      S3_BUCKET: ${{ secrets.STAGE_S3_BUCKET }}
      S3_REGION: ${{ secrets.STAGE_S3_BUCKET_REGION }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGE_CLOUDFRONT_DISTRIBUTION_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  #lint:
  #  uses: ./.github/workflows/rubocop.yml
  #test:
  #  uses: ./.github/workflows/parallel_ci.yml
  #  secrets: inherit
  #call_build_and_push:
  #  needs: test
  #  uses: ./.github/workflows/build.yml
  #  with:
  #    image_name: ${{ github.repository }}
  #    image_tag: ${{ github.ref_name }}
  #  secrets: inherit
  #deploy:
  #  needs: [test, call_build_and_push]
  #  uses: ./.github/workflows/_update_terraform.yml
  #  with:
  #    image_tag: ${{ github.ref_name }}
  #    deployment_environment: staging
  #  secrets: inherit

