name: Bump Version
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Set package.json version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          npm config set tag-version-prefix ''
          npm version ${{ github.event.inputs.releaseTag }} -m "Bump version to ${{ github.event.inputs.releaseTag }}"

          git push origin master --tags

          git tag
          echo "GOT HERE!"
          echo "{markdown content}" >> $GITHUB_STEP_SUMMARY