name: Bump Version
on:
  workflow_dispatch:
  
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  RACK_ENV: stage
  ENV_FILE: .env.stage

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    # CHECK OUT REPO
    - name: Git checkout
      uses: actions/checkout@v3
        
    - name: Extract variables
      shell: bash
      run: |
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "GIT_SHA_SHORT=$( git rev-parse --short ${{ github.sha }} )" >> $GITHUB_ENV
        echo "MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT
      id: extract_variables   
        # echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_OUTPUT
        # echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_OUTPUT
        # echo "TAG=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT
        # echo "GIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        # echo "GIT_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        # echo "MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_OUTPUT
      # id: extract_variables     
      
    - name: Print variables
      run: |
        echo "BRANCH = ${{ steps.extract_variables.outputs.BRANCH }}"
        echo "TAG = ${{ env.TAG }}"
        echo "GIT_SHA = ${{ env.GIT_SHA }}"
        echo "GIT_SHA_SHORT = ${{ senv.GIT_SH_SHORT }}"
        echo "MESSAGE = ${{ env.MESSAGE }}"
        # echo ${{ steps.extract_variables.outputs.BRANCH }}
        # echo ${{ steps.extract_variables.outputs.TAG }}
        # echo ${{ steps.extract_variables.outputs.GIT_SHA }}
        # echo ${{ steps.extract_variables.outputs.GIT_SHA_SHORT }}
        # echo ${{ steps.extract_variables.outputs.MESSAGE }}
