name: Bump version
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: false

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Set package.json version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          npm version ${{ github.event.inputs.releaseTag }} -no-git-tag-version
          
          git add package.json
          git commit -m "Adding lupo git variables for tag ${{ steps.extract_variables.outputs.GIT_TAG }}"
                    git add .
          git commit -m "Update package.json version field to ${{ github.event.inputs.releaseTag }}"
          git push
          git tags
          echo "GOT HERE!"