name: Bump version
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: false

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set package.json version
        run: |
          npm config set tag-version-prefix ''
          npm version ${{ github.event.inputs.releaseTag }} -no-git-tag-version

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push gh-origin HEAD:master --tags
