name: Bump Version
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Set package.json version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          npm config set tag-version-prefix ''
          npm version ${{ github.event.inputs.releaseTag }} -m "Bump version to ${{ github.event.inputs.releaseTag }}"

          git push origin master --tags

      - name: Success Summary
        if: ${{ success() }}
        run: |
          echo "### Package version bumped to:  ${{ github.event.inputs.releaseTag }}.  Release tag created." >> $GITHUB_STEP_SUMMARY

      - name: Failure Summary
        if: ${{ failure() }}
        run: |
          echo "### UNABLE TO BUMP VERSION/RELEASE TAG:  ${{ github.event.inputs.releaseTag }}." >> $GITHUB_STEP_SUMMARY