name: Cached
on:
  workflow_call:
    inputs:
      rack_env:
        required: true  
        type: string
      env_file:
        required: true
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print basic info in cached.yml
        run: |
          echo "ENV_FILE: ${{ inputs.env_file }}"
          echo "RACK_ENV: ${{ inputs.rack_env }}"
      #- name: Checkout
      #  uses: actions/checkout@v3
      - name: Get cached build
        uses: actions/cache@v3
        with:
          path: <path to the files you need>  # See the note below
          key: some-key
          restore-keys: |
            some-key
          #key: ${{ runner.os }}-buildx-${{ github.sha }}
          #restore-keys: |
          #  ${{ runner.os }}-buildx-${{ github.sha }}
