name: Notify
on:
  workflow_call:
    inputs:
      REPOSITORY:
        required: true
        type: string
      LATEST_RELEASE:
        required: true
        type: string
      BRANCH:
        required: true
        type: string
      TAG:
        required: true
        type: string
      GIT_SHA:
        required: true
        type: string
      GIT_SHA_SHORT:
        required: true
        type: string
      MESSAGE:
        required: true
        type: string
      SITE_NAME:
        required: true
        type: string
      SITE_URL:
        required: true
        type: string
      RACK_ENV:
        required: true
        type: string
      ENV_FILE:
        required: true
        type: string
    secrets:
      S3_BUCKET:
        required: true
      S3_REGION:
        required: true
      CLOUDFRONT_DISTRIBUTION_ID:
        required: true  
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Print variables
      run: |
        echo "REPOSITORY = ${{ inputs.REPOSITORY }}"
        echo "LATEST_RELEASE = ${{ inputs.LATEST_RELEASE }}"
        echo "BRANCH = ${{ inputs.BRANCH }}"
        echo "TAG = ${{ inputs.TAG }}"
        echo "GIT_SHA = ${{ inputs.GIT_SHA }}"
        echo "GIT_SHA_SHORT = ${{ inputs.GIT_SHA_SHORT }}"
        echo "MESSAGE = ${{ inputs.MESSAGE }}"
        echo "SITE_NAME = ${{ inputs.SITE_NAME }}"
        echo "SITE_URL = ${{ inputs.SITE_URL }}"
        echo "RACK_ENV = ${{ inputs.RACK_ENV }}"
        echo "ENV_FILE = ${{ inputs.ENV_FILE }}"
        echo "S3_BUCKET = ${{ secrets.S3_BUCKET }}"
        echo "S3_REGION = ${{ secrets.S3_REGION }}"
        echo "CLOUDFRONT_DISTRIBUTION_ID = ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}"
        echo "AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        echo "SLACK_WEBHOOK_URL = ${{ secrets.SLACK_WEBHOOK_URL }}"
        echo "GITHUB_RUN_NUMBER = ${{ env.GITHUB_RUN_NUMBER }}"
        echo "GITHUB_WORKFLOW = ${{ env.GITHUB_WORKFLOW }}"
        echo "github.actor = ${{ github.actor }}"
        echo "github.repository = ${{ github.repository }}"
        
        
    #- name: Notify Slack
    #  uses: edge/simple-slack-notify@master
    #  with:
    #    channel: '#ops'
    #    color: 'good'
    #    text: 'A new version of the <https://datacite.org|homepage> has been released.'
    #    failure_text: '${{ env.GITHUB_WORKFLOW }} (${{ env.GITHUB_RUN_NUMBER }}) build failed'
    #    fields: |
    #      [{ "title": "Committed by", "value": "<https://github.com/${{ github.repository }}/commits?author=${{ github.actor }}|${{ github.actor }}>", "short": true },
    #       { "title": "Commit SHA", "value": "<https://github.com/${{ github.repository }}/commit/${{ inputs.GIT_SHA }}|${{ inputs.GIT_SHA_SHORT }}>", "short": true },
    #       { "title": "Repository", "value": "<https://github.com/${{ github.repository }}|${{ github.repository }}>", "short": true },
    #       { "title": "Branch", "value": "<https://github.com/${{ github.repository }}/tree/master|${{ inputs.BRANCH }}>", "short": true },
    #       { "title": "Release", "value": "<https://github.com/${{ github.repository }}/releases/tag/${{ inputs.LATEST_RELEASE }}|${{ inputs.TAG }}>", "short": true }]
