name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: yarn install

      - name: Run Test Suite
        run: |
          yarn test:unit tests/

      - name: Test Package Build
        run: |
          yarn build --target wc --name data-metrics-badge 'src/components/DataMetricsBadge.vue'