name: Release Created
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
          always-auth: true

      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - run: |
          echo "Print release -  ${{ github.event.release.tag_name }}"
          yarn install
          yarn build --target wc --name data-metrics-badge 'src/components/DataMetricsBadge.vue'

      - run: |
          yarn publish

        env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}