name: Release Published
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build Package
        run: |
          yarn build --target wc --name data-metrics-badge 'src/components/DataMetricsBadge.vue'

      - name: Publish
        run: |
          npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
