name: Release Created
on:
  release:
    types: [created]
jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: |
          echo "Print release -  ${{ github.event.release.tag_name }}"
          yarn install

      - name: Set version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          npm version ${{ github.event.release.tag_name }}

          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git push gh-origin HEAD:master

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}