name: Simple
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - name: print env vars
        run: 
          echo -e "AWS_ACCESS_KEY_ID = ${{secrets.AWS_ACCESS_KEY_ID}}"
          echo -e "AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}"
          echo -e "S3_BUCKET = ${{secrets.S3_BUCKET}}"
          echo -e "S3_BUCKET_REGION = ${{secrets.S3_BUCKET_REGION}}"
          echo -e "DONE WITH JOB"
