name: Simple
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: print env vars
        run: |
          echo "AWS_ACCESS_KEY_ID = ${{secrets.AWS_ACCESS_KEY_ID}}"
          echo "AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}"
          echo "S3_BUCKET = ${{secrets.S3_BUCKET}}"
          echo "S3_BUCKET_REGION = ${{secrets.S3_BUCKET_REGION}}"
          echo "RUNNER_TEMP = $RUNNER_TEMP"
          #mkdir $RUNNER_TEMP/build
          echo "DONE WITH JOB"
      
      - name: create test files
        run: |  
          mkdir build
          echo "Hello world!" > build/hello.txt
          echo "Hello world! (2)" > ./build/hello2.txt
      
      - name: Deploy
        uses: reggionick/s3-deploy@v3.2.0
        with:
          folder: build
          bucket: ${{ secrets.STAGE_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: false
