name: Simple
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      
    steps:
      - name: print env vars(1)
        run: |
          echo "GITHUB_WORKFLOW = ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}"
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: print env vars(2)
        run: |
          echo "AWS_ACCESS_KEY_ID = ${{secrets.AWS_ACCESS_KEY_ID}}"
          echo "AWS_SECRET_ACCESS_KEY = ${{secrets.AWS_SECRET_ACCESS_KEY}}"
          echo "S3_BUCKET = ${{secrets.S3_BUCKET}}"
          echo "S3_BUCKET_REGION = ${{secrets.S3_BUCKET_REGION}}"
          echo "RUNNER_TEMP = $RUNNER_TEMP"
          #mkdir $RUNNER_TEMP/build
          echo "GITHUB_WORKFLOW = ${GITHUB_WORKFLOW}"
          echo "GITHUB_RUN_NUMBER = ${GITHUB_RUN_NUMBER}"
          echo "DONE WITH JOB"
    
      # NOTE THAT WE MUST USE env.S3_BUCKET IN THE IF
      - if: ${{ env.S3_BUCKET == 'bucket-skv-20230510' }}
        run: |
          echo 'DEPLOYING TO THE STAGING BUCKET!'
      - if: ${{ env.S3_BUCKET != 'bucket-skv-20230510' }}
        run: |
          echo 'DEPLOYING TO THE WRONG BUCKET!!!!'
      
      - name: create test files
        run: |  
          mkdir build
          echo "Hello world! (5)" > build/hello5.txt
          echo "Hello world! (6)" > ./build/hello6.txt
      
      - name: Deploy
        uses: reggionick/s3-deploy@master
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          invalidation: /
          delete-removed: false
