name: Test Shared
on:
  workflow_dispatch:
  
env:
  RACK_ENV: stage
  ENV_FILE: .env.stage
  
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      rack_env: ${{ env.RACK_ENV }}
      env_file: ${{ env.ENV_FILE }}
    steps:
      - run: echo "Exposing env vars"

  invoke-workflow:
    needs: vars
    name: "Workflow that needs env vars"      
    uses: ./.github/workflows/shared.yml
    with:
      rack_env: ${{ needs.vars.outputs.rack_env }}
      env_file: ${{ needs.vars.outputs.env_file }}
