name: GitHub Actions Demo - vercel_args
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    #inputs:
    #  vercelBuildWithoutCache:
    #    description: 'Vercel Build Without Cache'     
    #    default: 'false'
env:
  VERCEL_ARGS: ""
  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - name: set VERCEL_ARGS
      run: |
        echo "VERCEL_ARGS=--force" >> $GITHUB_ENV
      if: ${{ vars.VERCEL_NOCACHE  == 'true' }}
    - name: print env vars
      run: |
        echo -e "VERCEL_ARGS = ${{vars.VERCEL_ARGS}}"
        echo -e "VERCEL_ARGS_1 = ${{vars.VERCEL_ARGS_1}}"
    - name: print env vars - AGAIN
      run: |
        echo -e "VERCEL_ARGS = ${{vars.VERCEL_ARGS}}"
        echo -e "VERCEL_ARGS_1 = ${{vars.VERCEL_ARGS_1}}"
