name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    inputs:
      vercelBuildWithoutCache:
        description: 'Vercel Build Without Cache'     
        default: 'false'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Vercel Build Without Cache: ${{ github.event.inputs.vercelBuildWithoutCache }}" 
