name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
    inputs:
      vercelBuildWithoutCache:
        description: 'Vercel Build Without Cache'     
        default: 'false'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.inputs.vercelBuildWithoutCache  == 'true' }} || ${{ github.event.inputs.vercelBuildWithoutCache == '1' }}
        run: |
          echo "VERCEL_ARGS='--force'" >> $GITHUB_ENV
          echo "BUILD WITHOUT CACHE!! ${{env.VERCEL_ARGS}}"

