name: Test Cached
on:
  workflow_dispatch:
  
env:
  RACK_ENV: stage
  ENV_FILE: .env.stage
  
jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      rack_env: ${{ env.RACK_ENV }}
      env_file: ${{ env.ENV_FILE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test name
        run: | 
          echo "Exposing env vars"
          echo "RACK_ENV: ${{ env.RACK_ENV }}"
          echo "ENV_FILE: ${{ env.ENV_FILE }}"
          mkdir build
          echo "Hello world!" > "build/hello.txt"
          echo "PRINTING THE FILE!"
          cat build/hello.txt
          echo "PRINTING GITHUB VARS!"
          echo "REPOSITORY: ${{ github.repository }}"
          echo "BRANCH: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "SHORT SHA: $(git rev-parse --short ${{ github.sha }})"
      - uses: actions/cache@v3
        with:
          path: build
          key: assets-buildx-${{ github.sha }}
          restore-keys: |
            assets-buildx-${{ github.sha }}
          #key: ${{ runner.os }}-buildx-${{ github.sha }}
          #restore-keys: |
          #  ${{ runner.os }}-buildx-${{ github.sha }}

  invoke-workflow:
    needs: vars
    name: "Workflow that needs env vars"      
    uses: ./.github/workflows/cached.yml
    with:
      rack_env: ${{ needs.vars.outputs.rack_env }}
      env_file: ${{ needs.vars.outputs.env_file }}
