name: Test Shared
on:
  workflow_dispatch:
env:
  RACK_ENV: stage
  ENV_FILE: .env.stage

jobs:
  call_build_and_cache:
    uses: ./.github/workflows/shared.yml
    with:
      rack_env: $RACK_ENV
      env_file: $ENV_FILE
    secrets: inherit
