name: Test Shared
on:
  workflow_dispatch:
env:
  RACK_ENV: stage
  ENV_FILE: .env.stage

jobs:
  print_shared_info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Basic Info 1111
        run: |
          echo "ENV_FILE: $ENV_FILE"
          echo "RACK_ENV: $RACK_ENV"
  build_and_cache:
    uses: ./.github/workflows/shared.yml
    with:
      rack_env: ${{ env.RACK_ENV }}
      env_file: ${{ env.ENV_FILE }}
      #secrets: inherit
